name = "HubbardDiagonalization"
uuid = "aa2880e1-af8e-48e8-9ccc-27163daa77df"
version = "0.1.0"
authors = ["CoolSpy3 <coolspythree@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.10.15"
JuliaFormatter = "2.2.0"
LinearAlgebra = "^1.11.7"
Plots = "1.41.1"
TOML = "1.0.3"
UnicodePlots = "3.8.1"
ZipFile = "0.10.1"
