[parameters]
num_colors = 2
t = 2
u_test = 0.0
U = 2.0

[plot]
# Plot Characteristics
width = 1000
height = 800

# Ranges
T_min = 0.02
T_max = 10
T_step = 0.02
u_min = -20
u_max = 20
u_step = 0.05

# Specific Plots to Generate
T_fixed_plots = [0.02, 0.1, 0.5]
u_fixed_plots = [-0.5, 0.0, 0.5]
# Observables to Plot in the format:
# [subplots]
# where each subplot is:
#   [[generated observable names], [csv data names (from overlay_data)]]
observables = [
	[["Density"], ["Densities"]],
	[["Double Occupancies"], ["Doubleoccupancies"]],
	[["Energy"], ["Energies"]],
	[["Local Moment"], []],
	[["Entropy"], ["Entropies"]],
	[["C_spin"], ["CNNs"]],
]

overlay_data = "tests/grids/2x2_ED_Repulsive_SUN_OBC.zip/2x2_ED_Repulsive_SUN_OBC/2x2_N3_U2/"

nlce_orders = [1, 2, 3]

[graph]
num_sites = 4
